image:
  repository: bitnami/keycloak
  tag: 20.0.3-debian-11-r14

auth:
  adminUser: admin
  adminPassword: "ygmqvdcx9me"

production: true
proxy: edge

extraEnvVars:
  - name: KC_DB_SCHEMA
    value: "keycloak_dev"

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.5
    memory: 512Mi

service:
  type: ClusterIP

ingress:
  enabled: true
  hostname: idp-dev.mydomain.net
  extraTls:
  - hosts:
    - idp-dev.mydomain.net
    secretName: tls-secret

postgresql:
  enabled: false

externalDatabase:
  host: postgres-15
  port: 5432
  user: keycloak_dev
  database: keycloak_dev
  password: "GBnX9TVnmi"
